In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from backprop.element import Element
from backprop.activations import sigmoid
from backprop.functions import log

In [4]:
import numpy as np

In [5]:
p = Element([1., 2., 3.,]).T
q = Element([4., 5., 6.,]).T

p.T @ q

Element(value=[[32.]], grad=[[0.]], op=@)

In [7]:
q = Element([np.exp(1.0), np.exp(2.0), 3.0, 4.0])

log(q)

Element(value=[[1.         2.         1.09861229 1.38629436]], grad=[[0. 0. 0. 0.]], op=ln)

In [5]:
x = Element([1.0, 2.0, 3.0, 4.0]).T
y = Element([6.0, 6., 6., 6.]).T

z = (x * y)
a = Element([0.25, 0.25, 0.25, 0.25]).T
b = a.T @ z
b.backward()

print('x: ', x.T)
print('y: ', y.T)
print('z: ', z.T)

print('a: ', a.T)
print('b: ', b.T)

x:  Element(value=[[1. 2. 3. 4.]], grad=[[0. 0. 0. 0.]], op=T)
y:  Element(value=[[6. 6. 6. 6.]], grad=[[0. 0. 0. 0.]], op=T)
z:  Element(value=[[ 6. 12. 18. 24.]], grad=[[0. 0. 0. 0.]], op=T)
a:  Element(value=[[0.25 0.25 0.25 0.25]], grad=[[0. 0. 0. 0.]], op=T)
b:  Element(value=[[15.]], grad=[[0.]], op=T)


In [6]:
q = Element(0.12)
r = q * q
s = r * r
t = sigmoid(s)

t.backward()
print('t: ', t)
print('s: ', s)
print('r: ', r)
print('q: ', q)

t:  Element(value=[[0.50005184]], grad=[[1.]], op=σ)
s:  Element(value=[[0.00020736]], grad=[[0.25]], op=x)
r:  Element(value=[[0.0144]], grad=[[0.0072]], op=x)
q:  Element(value=[[0.12]], grad=[[0.001728]], op=None)


In [7]:
x = Element([1., 2., 3., 4.,]).T

y = x.T @ x

y.backward()

print('y: ', y)
print('x: ', x)

y:  Element(value=[[30.]], grad=[[1.]], op=@)
x:  Element(value=[[1.]
 [2.]
 [3.]
 [4.]], grad=[[2.]
 [4.]
 [6.]
 [8.]], op=T)


In [8]:
w = Element([1, 1, 1]).T
x = Element([-1, -1, -1]).T
b = Element(10)

a = sigmoid(w.T @ x + b)

a.backward()

print('a: ', a.T)
print('w: ', w.T)
print('x: ', x.T)
print('b: ', b.T)

a:  Element(value=[[0.99908895]], grad=[[0.]], op=T)
w:  Element(value=[[1. 1. 1.]], grad=[[0. 0. 0.]], op=T)
x:  Element(value=[[-1. -1. -1.]], grad=[[0. 0. 0.]], op=T)
b:  Element(value=[[10.]], grad=[[0.]], op=T)


In [10]:
W = Element(
    [
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]
    ])
x = Element([-1, -1, -1]).T
b = Element([4., 5., 6.,]).T

z = sigmoid(W.T @ x + b)
mu = Element([0.33, .33, .34]).T
L = z.T @ mu
L.backward()

print('z: ', z)
print('w: ', W)
print('x: ', x)
print('b: ', b)

z:  Element(value=[[0.73105858]
 [0.88079708]
 [0.95257413]], grad=[[0.33]
 [0.33]
 [0.34]], op=σ)
w:  Element(value=[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], grad=[[-0.06488194 -0.03464788 -0.01536006]
 [-0.06488194 -0.03464788 -0.01536006]
 [-0.06488194 -0.03464788 -0.01536006]], op=None)
x:  Element(value=[[-1.]
 [-1.]
 [-1.]], grad=[[0.11488989]
 [0.11488989]
 [0.11488989]], op=T)
b:  Element(value=[[4.]
 [5.]
 [6.]], grad=[[0.06488194]
 [0.03464788]
 [0.01536006]], op=T)


In [21]:
b = Element([4., 5., 6.,]).T

W = Element(
    [
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]
    ])

X = Element(
    [
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]
    ])

((W.T @ X @ b).T @ b).backward()

print('W: ', W)
print('X: ', X)


W:  Element(value=[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], grad=[[60. 75. 90.]
 [60. 75. 90.]
 [60. 75. 90.]], op=None)
X:  Element(value=[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], grad=[[16. 20. 24.]
 [20. 25. 30.]
 [24. 30. 36.]], op=None)
